worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        server_name ciphernest.local;

        location / {
            proxy_pass http://platform:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /cn01/ {
            proxy_pass http://cn01-stego:8081/;
            proxy_set_header Host $host;
        }

        location /cn02/ {
            proxy_pass http://cn02-webapp:8082/;
            proxy_set_header Host $host;
        }

        location /cn03/ {
            alias /usr/share/nginx/cn03/;
            autoindex on;
        }

        location /cn04/ {
            proxy_pass http://cn04-forensics:8084/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
